// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmvmdsxaeqhcmqdtkzuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdm1kc3hhZXFoY21xZHRrenV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTU4MjMsImV4cCI6MjA3MjI5MTgyM30.N7uGry_vk5I_3CjF7fkYYOzyCisDCoBFIXD3VGzLVMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});